// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mcbebu/ALTER-TABLE/ent/order"
	"github.com/mcbebu/ALTER-TABLE/ent/predicate"
	"github.com/mcbebu/ALTER-TABLE/ent/schema"
	"github.com/mcbebu/ALTER-TABLE/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetAddresses sets the "addresses" field.
func (uu *UserUpdate) SetAddresses(s []schema.Address) *UserUpdate {
	uu.mutation.SetAddresses(s)
	return uu
}

// AppendAddresses appends s to the "addresses" field.
func (uu *UserUpdate) AppendAddresses(s []schema.Address) *UserUpdate {
	uu.mutation.AppendAddresses(s)
	return uu
}

// SetLeaveParcel sets the "leaveParcel" field.
func (uu *UserUpdate) SetLeaveParcel(b bool) *UserUpdate {
	uu.mutation.SetLeaveParcel(b)
	return uu
}

// SetNillableLeaveParcel sets the "leaveParcel" field if the given value is not nil.
func (uu *UserUpdate) SetNillableLeaveParcel(b *bool) *UserUpdate {
	if b != nil {
		uu.SetLeaveParcel(*b)
	}
	return uu
}

// SetInstructions sets the "instructions" field.
func (uu *UserUpdate) SetInstructions(s []string) *UserUpdate {
	uu.mutation.SetInstructions(s)
	return uu
}

// AppendInstructions appends s to the "instructions" field.
func (uu *UserUpdate) AppendInstructions(s []string) *UserUpdate {
	uu.mutation.AppendInstructions(s)
	return uu
}

// SetNotifications sets the "notifications" field.
func (uu *UserUpdate) SetNotifications(b [4]bool) *UserUpdate {
	uu.mutation.SetNotifications(b)
	return uu
}

// SetOrdersID sets the "orders" edge to the Order entity by ID.
func (uu *UserUpdate) SetOrdersID(id int) *UserUpdate {
	uu.mutation.SetOrdersID(id)
	return uu
}

// SetNillableOrdersID sets the "orders" edge to the Order entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableOrdersID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetOrdersID(*id)
	}
	return uu
}

// SetOrders sets the "orders" edge to the Order entity.
func (uu *UserUpdate) SetOrders(o *Order) *UserUpdate {
	return uu.SetOrdersID(o.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearOrders clears the "orders" edge to the Order entity.
func (uu *UserUpdate) ClearOrders() *UserUpdate {
	uu.mutation.ClearOrders()
	return uu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, UserMutation](ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Addresses(); ok {
		_spec.SetField(user.FieldAddresses, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldAddresses, value)
		})
	}
	if value, ok := uu.mutation.LeaveParcel(); ok {
		_spec.SetField(user.FieldLeaveParcel, field.TypeBool, value)
	}
	if value, ok := uu.mutation.Instructions(); ok {
		_spec.SetField(user.FieldInstructions, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedInstructions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldInstructions, value)
		})
	}
	if value, ok := uu.mutation.Notifications(); ok {
		_spec.SetField(user.FieldNotifications, field.TypeJSON, value)
	}
	if uu.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.OrdersTable,
			Columns: []string{user.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.OrdersTable,
			Columns: []string{user.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetAddresses sets the "addresses" field.
func (uuo *UserUpdateOne) SetAddresses(s []schema.Address) *UserUpdateOne {
	uuo.mutation.SetAddresses(s)
	return uuo
}

// AppendAddresses appends s to the "addresses" field.
func (uuo *UserUpdateOne) AppendAddresses(s []schema.Address) *UserUpdateOne {
	uuo.mutation.AppendAddresses(s)
	return uuo
}

// SetLeaveParcel sets the "leaveParcel" field.
func (uuo *UserUpdateOne) SetLeaveParcel(b bool) *UserUpdateOne {
	uuo.mutation.SetLeaveParcel(b)
	return uuo
}

// SetNillableLeaveParcel sets the "leaveParcel" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableLeaveParcel(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetLeaveParcel(*b)
	}
	return uuo
}

// SetInstructions sets the "instructions" field.
func (uuo *UserUpdateOne) SetInstructions(s []string) *UserUpdateOne {
	uuo.mutation.SetInstructions(s)
	return uuo
}

// AppendInstructions appends s to the "instructions" field.
func (uuo *UserUpdateOne) AppendInstructions(s []string) *UserUpdateOne {
	uuo.mutation.AppendInstructions(s)
	return uuo
}

// SetNotifications sets the "notifications" field.
func (uuo *UserUpdateOne) SetNotifications(b [4]bool) *UserUpdateOne {
	uuo.mutation.SetNotifications(b)
	return uuo
}

// SetOrdersID sets the "orders" edge to the Order entity by ID.
func (uuo *UserUpdateOne) SetOrdersID(id int) *UserUpdateOne {
	uuo.mutation.SetOrdersID(id)
	return uuo
}

// SetNillableOrdersID sets the "orders" edge to the Order entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableOrdersID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetOrdersID(*id)
	}
	return uuo
}

// SetOrders sets the "orders" edge to the Order entity.
func (uuo *UserUpdateOne) SetOrders(o *Order) *UserUpdateOne {
	return uuo.SetOrdersID(o.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearOrders clears the "orders" edge to the Order entity.
func (uuo *UserUpdateOne) ClearOrders() *UserUpdateOne {
	uuo.mutation.ClearOrders()
	return uuo
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks[*User, UserMutation](ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Addresses(); ok {
		_spec.SetField(user.FieldAddresses, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldAddresses, value)
		})
	}
	if value, ok := uuo.mutation.LeaveParcel(); ok {
		_spec.SetField(user.FieldLeaveParcel, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.Instructions(); ok {
		_spec.SetField(user.FieldInstructions, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedInstructions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldInstructions, value)
		})
	}
	if value, ok := uuo.mutation.Notifications(); ok {
		_spec.SetField(user.FieldNotifications, field.TypeJSON, value)
	}
	if uuo.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.OrdersTable,
			Columns: []string{user.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.OrdersTable,
			Columns: []string{user.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
