// Code generated by ent, DO NOT EDIT.

package user

import (
	"github.com/mcbebu/ALTER-TABLE/ent/schema"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMobileNumber holds the string denoting the mobilenumber field in the database.
	FieldMobileNumber = "mobile_number"
	// FieldAddresses holds the string denoting the addresses field in the database.
	FieldAddresses = "addresses"
	// FieldLeaveParcel holds the string denoting the leaveparcel field in the database.
	FieldLeaveParcel = "leave_parcel"
	// FieldInstructions holds the string denoting the instructions field in the database.
	FieldInstructions = "instructions"
	// FieldNotifications holds the string denoting the notifications field in the database.
	FieldNotifications = "notifications"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "orders"
	// OrdersInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OrdersInverseTable = "orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "user_orders"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldMobileNumber,
	FieldAddresses,
	FieldLeaveParcel,
	FieldInstructions,
	FieldNotifications,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MobileNumberValidator is a validator for the "mobileNumber" field. It is called by the builders before save.
	MobileNumberValidator func(string) error
	// DefaultAddresses holds the default value on creation for the "addresses" field.
	DefaultAddresses []schema.Address
	// DefaultLeaveParcel holds the default value on creation for the "leaveParcel" field.
	DefaultLeaveParcel bool
	// DefaultInstructions holds the default value on creation for the "instructions" field.
	DefaultInstructions []string
	// DefaultNotifications holds the default value on creation for the "notifications" field.
	DefaultNotifications [4]bool
)
