// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Shipper is the predicate function for shipper builders.
type Shipper func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
